### PR TITLE
Option interface help message getter to allow for custom formatting.

### PR DESCRIPTION
**Pull request by ryjen**
Pretty simple change.  Just had a need to have a different format that PrintOptions and was missing the help text.

### CODE REVIEW

**Comment by sam-github** [comment]
Should it have a test case?

**Comment by ryjen** [comment]
> Should it have a test case?

Good call thanks, updated.  Should suffice.

**Comment by sam-github** [comment]
LGTM, but this isn't my repo :-)

**Comment by pborman** [comment]
Well, better late than never, right?!

Thank you

**Pull request merged**
